export enum NsIcon {
   Close = 'close',
   Menu = 'menu',
   Build = 'build',
   AccountCircle = 'account_circle',
   Person = 'person',
   PersonOutline = 'person_outline',
   Search = 'search',
   Delete = 'delete_outline',
   SortAsc = 'text_rotation_down',
   SortDesc = 'text_rotate_up',
   Add = 'add',
   Edit = 'create',
   Face = 'face',
   Error = 'error',
   Car = 'directions_car',
   ArrowBack = 'arrow_back',
   Calendar = 'calendar_today',
   Time = 'access_time',
   ArrowBackCalendar = 'arrow_back_ios',
   ArrowForwardCalendar = 'arrow_forward_ios',
   Money = 'money',
   List = 'list',
   Details = 'details',
   Refresh = 'refresh',
   Link = 'link',
}
